Tc/schedule form
House-on-a-Rock/tjc-scheduling-web pull request #33
Opened 2020-11-11 04:49 UTC by CedThen

2020-11-11 14:58 UTC, CedThen commented
It looks a little bit rough but it does what its supposed to!

2020-11-11 17:33 UTC, showduhtung commented
hmm so you're actually missing a few things, validations for each form input

2020-11-11 17:36 UTC, showduhtung requested changes
once you make the changes to validation, you have my approval and you can go ahead and merge

2020-11-11 17:36 UTC, showduhtung commented on src/components/Main/Schedule/NewScheduleForm.tsx
> +      <button onClick={() => onSubmit(scheduleTitle, startDate, endDate, view, team)}>
this function should only fire if all validations are met.
1) Title shouldn't be longer than 32 characters
2) all fields must be filled and not null/empty

2020-11-12 04:23 UTC, hchiam commented on src/components/Main/Schedule/Home.tsx
> +  // useSpinner();
@CedThen already showed me a problem with useSpinner not playing nice with react query useMutation. Looks like we'll need a more involved solution for the spinner. I'll look into maybe an interface/wrapper to make it easy to specify when to start/stop upon API completion.

2020-11-12 04:26 UTC, hchiam commented on src/components/Main/Schedule/Home.tsx
> +  // if (status === 'loading') return <div>loading...</div>; // loading state
i think this can be deleted altogether - this never gets run when i tried it out for some reason

2020-11-12 04:43 UTC, hchiam reviewed
Actually, I ran your branch `tc/schedule-form` just now and the spinner seems to work fine on my machine. 
[EDIT: @CedThen - I got a fix for the spinner [here](https://github.com/House-on-a-Rock/tjc-scheduling-web/pull/36/files#diff-7b4f7e8958ec472ac00c2ace4e37d1e0f6b4508eb484c2d006e73be0e52a3695)]

2020-11-13 00:17 UTC, hchiam commented on src/components/Main/Schedule/Home.tsx
> +  // useSpinner();
@CedThen - I got a fix for the spinner [here](https://github.com/House-on-a-Rock/tjc-scheduling-web/pull/36/files#diff-7b4f7e8958ec472ac00c2ace4e37d1e0f6b4508eb484c2d006e73be0e52a3695)

2020-11-13 16:34 UTC, merged